apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: django-pdb
  namespace: inclusive-world-portal
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: django
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: celeryworker-pdb
  namespace: inclusive-world-portal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: celeryworker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  namespace: inclusive-world-portal
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx
