apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inclusive-world-ingress
  namespace: inclusive-world-portal
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: inclusiveworld.pasuko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inclusiveworld-ingress
                port:
                  number: 9000
